site_name: NebulaGraph Database 手册
site_description: Documentation for NebulaGraph Database 
site_author: NebulaGraph 
site_url: https://docs.nebula-graph.com.cn/ 
repo_name: 'vesoft-inc/nebula' 
repo_url: 'https://github.com/vesoft-inc/nebula' 
docs_dir: docs-2.0 
copyright: Copyright &copy; 2023 NebulaGraph - 浙ICP备20010487号
 
# modify when release: 
edit_uri: 'https://github.com/vesoft-inc/nebula-docs-cn/edit/v3.4.3/docs-2.0/'  

# Configuration
theme:
  name: material
  custom_dir: overrides
# git repo icon
  icon:
    repo: fontawesome/brands/github
  logo: 'https://docs-cdn.nebula-graph.com.cn/figures/vesoft-nebula-logo-white22-12-21.png'
  favicon: 'https://docs-cdn.nebula-graph.com.cn/figures/favicon.ico'
  # Change color in `stylesheets > extra.css`
  palette:
    - scheme: nebula
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - header.autohide
    - content.tabs.link
  language: 'zh'

extra_css:
  - stylesheets/logo.css
  - stylesheets/note.css
  - stylesheets/extra.css
  - css/version-select.css

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
#      toc_depth: 3
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs-2.0/reuse/
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed

# Plugins
plugins:
  - search # 这个是原有的 mkdocs 搜索插件， 如果想使用algolia搜索，请注释掉这个插件
  - macros:
      include_dir: docs-2.0/reuse/
  - git-revision-date-localized
# modify when release: 
  - exclude:
# Exclude files with unix-style wildcards (globs)
      glob:
# Exclude all files in a directory. The path starts with the directory name in docs-2.0, such as `20.appendix/*`.
        - nebula-flink/*
        - CHANGELOG.md
        # - nebula-cloud/*
        - nebula-cloud.md
        - nebula-cloud/nebula-cloud-on-azure/*
        - spark-connector/*
        - 4.deployment-and-installation/5.zone.md
        - 4.deployment-and-installation/3.upgrade-nebula-graph/upgrade-nebula-from-200-to-latest.md
        # ent.begin
        # - 3.ngql-guide/6.functions-and-expressions/17.ES-function.md
        # - 4.deployment-and-installation/deploy-license.md
        # - 5.configurations-and-logs/2.log-management/audit-log.md
        # - 7.data-security/1.authentication/4.ldap.md
        # - graph-computing/0.deploy-controller-analytics.md
        # - graph-computing/nebula-analytics.md
        # - graph-computing/use-explorer.md
        # - nebula-exchange/use-exchange/ex-ug-export-from-nebula.md
        # - nebula-operator/8.custom-cluster-configurations/8.3.balance-data-when-scaling-storage.md
        # - nebula-operator/10.backup-restore-using-operator.md
        # - synchronization-and-migration/replication-between-clusters.md
        # - 20.appendix/8.about-license/
        # - nebula-dashboard-ent/4.cluster-operator/operator/scale.md
        # - 6.monitor-and-metrics/3.bbox/
        # - backup-and-restore/nebula-br-ent/
        # ent.end
        # comm.begin
        # comm.end

# Exclude the file with the following file name.
#        - abc.md
# Exclude files with regular expressions (regexes)
#    regex:
#      - '.*\.(tmp|bin|tar)$'

# modify when release: 
  - with-pdf:
      copyright: 2023 vesoft Inc.
      cover_subtitle: v3.4.3
      author: 陈梦阳，梁振亚，黄凤仙
      cover: true
      back_cover: true
      cover_logo: 'https://cloud-cdn.nebula-graph.com.cn/nebula-for-pdf.png'
      output_path: pdf/NebulaGraph-CN.pdf

extra_javascript:
  - js/version-select.js      
  - js/config.js
  - js/jquery.js
  - js/init.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # js about docs search logic
  - https://www-cdn.nebula-graph.com.cn/nebula-docs/nebula-docs.7e772ed81c779cacbefc.js

# modify when release: 
extra:
  # For conditional rendering
  # Valid options: enterprise, community, both
  # enterprise means this version is for the Enterprise only. And so on in a similar fashion
  database_edition: both
  # Language selector.
  alternate:
    - name: English
      link: https://docs.nebula-graph.io/
      lang: en
  # Google Analytics.
  analytics:
    provider: google
    property: UA-60523578-15
  # branch represents code names (git clone). release represents version number used in texts.
  version:
    method: mike
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/vesoft-inc/nebula-docs-cn'
  nebula:
    release: 3.4.3
    nightly: nightly
    master: master
    base20: 2.0
    base200: 2.0.0
    branch: release-3.4
    tag: v3.4.3
  studio:
    base111b: 1.1.1-beta
    base220: 2.2.1
    base300: 3.0.0
    release: 3.6.0
    tag: v3.6.0
  explorer:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  exchange_ent:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  exchange:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  importer:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  algorithm:
    release: 3.0.0
    branch: v3.0.0
    tag: v3.0.0
  plato:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  sparkconnector:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  flinkconnector:
    release: 3.3.0
    branch: release-3.3
    tag: v3.3.0
  dockercompose:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  dashboard:
    release: 3.4.0
    tag: v3.4.0
    base100: 1.0.0
    branch: release-3.4
  dashboard_ent:
    release: 3.4.2
    tag: v3.4.2
    branch: release-3.4
  console:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  br:
    release: 3.3.0
    branch: release-3.3
    tag: v3.3.0
  br_ent:
    release: 3.4.1
    tag: v3.4.1
  agent:
    release: 3.4.0
    tag: v3.4.0
  cpp:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  java:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  python:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  go:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  bench:
    release: 1.2.0
    branch: release-1.2
    tag: v1.2.0
  operator:
    release: 1.4.2
    tag: v1.4.2
    branch: release-1.4
    upgrade_from: 3.0.0
    upgrade_to: 3.4.0
  exporter:
    release: 3.3.0
    branch: release-3.3
    tag: v3.3.0
  gateway:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  bbox:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  cloud:
    azureRelease: 3.1.1 # Azure云兼容的最新内核版本
    aliyunRelease: 3.4.3 # 阿里云兼容的最新内核版本
    azureLatestRelease: 3.1.0 # 支持Azure云的最新文档版本
    aliyunLatestRelease: 3.4.3 # 支持阿里云的最新文档版本
  ent:
    ent_begin: <!-- -->       #文档包含企业版时需补全该注释（<!-- -->），只包含社区版时只保留注释头（<!--）
    ent_end: <!-- -->      #文档包含企业版时需补全该注释（<!-- -->），只包含社区版时只保留注释尾（-->）


nav:

  - 悦数图数据库（公有云）:
    - 什么是悦数图数据库（公有云）: nebula-cloud/1.what-is-cloud.md
    - 悦数图数据库阿里云版:
      - 创建服务实例: nebula-cloud/nebula-cloud-on-alibabacloud/1.create-service-instance.md
      - 使用服务实例: nebula-cloud/nebula-cloud-on-alibabacloud/2.use-cloud-services.md
      - 扩缩容服务: nebula-cloud/nebula-cloud-on-alibabacloud/4.scaling-services.md
      - 删除服务实例: nebula-cloud/nebula-cloud-on-alibabacloud/3.delete-service-instance.md

 
 
  - PDF: ./pdf/NebulaGraph-CN.pdf
